application: regxplorer
version: 1
runtime: go
api_version: go1

handlers:
# static directory holds images, css, etc
- url: /static
  static_dir: static
# everything else goes to the Go program
- url: /.*
  script: _go_app
